### PR TITLE
Adding composer.json

### PR DESCRIPTION
**Pull request by ajibarra**
Adding composer.json

### CODE REVIEW

**Comment by josegonzalez** [comment]
@tigrang mind adding to packagist?

**Comment by tigrang** [comment]
@josegonzalez its already on there

**Comment by ajibarra** [comment]
It was submitted by other user. The requires section is wrong (PHP 5.3 instead of 5.4). Is there a way to update it there?

**Comment by tigrang** [comment]
@ajibarra Fixed

**Pull request merged**
